name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: armv7-unknown-linux-musleabihf
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target armv7-unknown-linux-musleabihf
    - name: Run tests
      run: cargo test --verbose
